Repository SITE-2022-W6/The-Foodie-Express-UI, pull requests merged in 2022-08, with the labels that each got.

#18 Ac frontend
  package-lock.json
  src/components/App/App.jsx
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.css
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
  src/components/ItemView/ItemView.jsx
  src/components/Navbar/Navbar.jsx
  src/components/RestaurantView/RestaurantView.css
  src/components/RestaurantView/RestaurantView.jsx
  src/services/apiClient.jsx
Labels: enhancement

#19 Added distance for each restuarant
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
Labels: enhancement

#21 Ac frontend
  public/banner.svg
  public/footerIcon.svg
  src/components/App/App.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
  src/components/Footer/Footer.jsx
  src/components/ItemView/ItemView.jsx
  src/components/Loading/Loading.css
  src/components/Loading/Loading.jsx
  src/components/RestaurantView/RestaurantView.css
  src/components/RestaurantView/RestaurantView.jsx
Labels: enhancement

#22 Bugfix 1
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/banner.json
Labels: bug

#24 Display message when there is an empty restaurant list
  src/components/Dashboard/Dashboard.jsx
  src/services/apiClient.jsx
Labels: bug

#26 Refactor api client
  src/components/Dashboard/Dashboard.jsx
  src/services/apiClient.jsx
Labels: refactor

#27 Ac frontend
  public/notfound.png
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.css
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
  src/components/ItemView/ItemView.jsx
  src/components/Landing/Landing.css
  src/components/Landing/Landing.jsx
  src/components/LocationSearchBar/LocationSearchBar.css
  src/components/LocationSearchBar/LocationSearchBar.jsx
  src/components/Login/Login.css
  src/components/Login/Login.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.jsx
  src/components/Register/Register.css
  src/components/Register/Register.jsx
  src/components/RestaurantView/RestaurantView.jsx
Labels: enhancement

#29 Ac frontend
  constants.js
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/RestaurantCard/RestaurantCard.css
  src/components/Dashboard/RestaurantCard/RestaurantCard.jsx
  src/components/ItemView/ItemView.css
  src/components/ItemView/ItemView.jsx
  src/components/Landing/Landing.jsx
  src/components/Modal/Modal.css
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/NotFound/NotFound.jsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.jsx
  src/components/Profile/RecentReview/RecentReview.css
  src/components/Profile/RecentReview/RecentReview.jsx
  src/components/Profile/UpdateReview/UpdateReview.css
  src/components/Profile/UpdateReview/UpdateReview.jsx
  src/components/RestaurantView/RestaurantView.css
  src/components/RestaurantView/RestaurantView.jsx
  src/components/banner.json
  src/components/data.json
  src/services/apiClient.jsx
Labels: enhancement

#30 Pref fix
  src/components/Dashboard/Dashboard.jsx
  src/components/ItemView/ItemView.jsx
  src/services/apiClient.jsx
Labels: enhancement
